// ===== JCam (camera) =====
  const JCamState = { stream:null, facing:null, video:null, canvas:null };
  function JCam_status(msg){ try{ const s=document.getElementById('jcamStatus'); if(s) s.textContent=msg||''; }catch(e){} }
  function JCam_httpsOkay(){ try{ return location.protocol==='https:' || location.hostname==='localhost' || location.hostname==='127.0.0.1'; }catch(e){ return false; } }
  function JCam_mediaSupported(){ try{ return !!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia); }catch(e){ return false; } }
  function JCam_buildConstraints(facing){ return { video:{ facingMode: facing? {ideal:facing}:undefined, width:{ideal:1920}, height:{ideal:1080} }, audio:false }; }
  function JCam_applyMirror(){ try{ if(!JCamState.video) return; JCamState.video.style.transform = (JCamState.facing==='user')? 'scaleX(-1)' : ''; }catch(e){} }
  function JCam_fit(){ try{ const app=document.getElementById('jcamApp'); if(!app) return; const maxH=Math.max(320,(window.visualViewport?.height||window.innerHeight)-8); const h=app.getBoundingClientRect().height; if(h>maxH){ app.style.height=Math.max(320,maxH)+'px'; } else { app.style.height=''; } }catch(e){} }
  window.addEventListener('resize', JCam_fit); window.addEventListener('orientationchange', JCam_fit);
  async function JCam_open(){ try{ const win=document.getElementById('jcamApp'); if(!win) return; JCamState.video=document.getElementById('jcamVideo')||null; JCamState.canvas=document.getElementById('jcamCanvas')||null; const saveBtn=document.getElementById('jcamSaveBtn'); const retakeBtn=document.getElementById('jcamRetakeBtn'); const shutter=document.getElementById('jcamShutterBtn'); if(saveBtn) saveBtn.style.display='none'; if(retakeBtn) retakeBtn.style.display='none'; if(shutter) shutter.style.display='inline-block'; const flip=document.getElementById('jcamFlipBtn'); if(flip) flip.disabled=false; if(!JCamState.facing){ try{ JCamState.facing=localStorage.getItem('jackosCameraFacing')||'user'; }catch(e){ JCamState.facing='user'; } } win.style.display='block'; JCam_status('Opening camera…'); JCam_fit(); if(!JCam_httpsOkay()){ JCam_status('Camera requires HTTPS or localhost'); return; } if(!JCam_mediaSupported()){ JCam_status('Camera not supported on this browser'); return; } await JCam_start(); } catch(err){ console.warn('JCam_open error', err); JCam_status('Unable to open: '+(err?.message||String(err))); } }
  async function JCam_close(){ try{ await JCam_stop(); }catch(e){} try{ const win=document.getElementById('jcamApp'); if(win) win.style.display='none'; }catch(e){} }
  async function JCam_start(){ const tryLists=[ JCam_buildConstraints(JCamState.facing), {video:true,audio:false}, {video:{facingMode:JCamState.facing},audio:false} ]; await JCam_stop().catch(()=>{}); for(let i=0;i<tryLists.length;i++){ try{ const stream=await navigator.mediaDevices.getUserMedia(tryLists[i]); JCamState.stream=stream; if(JCamState.video){ JCamState.video.srcObject=stream; try{ await JCamState.video.play(); }catch(e){} await new Promise(res=>{ let d=false; const done=()=>{ if(!d){ d=true; res(); } }; if(JCamState.video) JCamState.video.onloadedmetadata=done; setTimeout(done,500); }); JCam_applyMirror(); JCam_fit(); } JCam_status('Camera ready'); return; }catch(err){ console.warn('JCam_start attempt',i+1,'failed:', err?.message||err); } } if(!JCam_httpsOkay()) JCam_status('Camera requires HTTPS or localhost'); else JCam_status('Unable to open camera on this device/browser'); }
  async function JCam_stop(){ try{ if(JCamState.stream){ for(const t of JCamState.stream.getTracks()){ try{ t.stop(); }catch(e){} } } }catch(e){} finally{ JCamState.stream=null; try{ if(JCamState.video) JCamState.video.srcObject=null; }catch(e){} } }
  function JCam_flip(){ try{ JCamState.facing = (JCamState.facing==='environment')? 'user':'environment'; try{ localStorage.setItem('jackosCameraFacing', JCamState.facing); }catch(e){} JCam_start(); }catch(e){ console.warn('JCam_flip error', e); JCam_status('Flip failed'); } }
  function JCam_shoot(){ try{ const v=JCamState.video, c=JCamState.canvas; if(!v||!c) return; const w=v.videoWidth||v.clientWidth||1280, h=v.videoHeight||v.clientHeight||720; c.width=w; c.height=h; const ctx=c.getContext('2d'); ctx.save(); if(JCamState.facing==='user'){ ctx.translate(w,0); ctx.scale(-1,1); } ctx.drawImage(v,0,0,w,h); ctx.restore(); v.style.display='none'; c.style.display='block'; const saveBtn=document.getElementById('jcamSaveBtn'); const retakeBtn=document.getElementById('jcamRetakeBtn'); const shutter=document.getElementById('jcamShutterBtn'); if(saveBtn) saveBtn.style.display='inline-block'; if(retakeBtn) retakeBtn.style.display='inline-block'; if(shutter) shutter.style.display='none'; JCam_status('Preview • Ready to save'); JCam_fit(); }catch(e){ console.warn('JCam_shoot error', e); JCam_status('Failed to capture: '+(e?.message||String(e))); } }
  function JCam_retake(){ try{ const v=JCamState.video, c=JCamState.canvas; if(!v||!c) return; c.style.display='none'; v.style.display='block'; JCam_applyMirror(); const saveBtn=document.getElementById('jcamSaveBtn'); const retakeBtn=document.getElementById('jcamRetakeBtn'); const shutter=document.getElementById('jcamShutterBtn'); if(saveBtn) saveBtn.style.display='none'; if(retakeBtn) retakeBtn.style.display='none'; if(shutter) shutter.style.display='inline-block'; JCam_status('Ready'); JCam_fit(); }catch(e){} }
  function JCam_canvasToBlob(canvas,type='image/png',quality=0.92){ return new Promise((resolve,reject)=>{ try{ if(typeof canvas.toBlob==='function'){ canvas.toBlob(b=>resolve(b),type,quality); } else { const dataURL=canvas.toDataURL(type,quality); const arr=dataURL.split(','); const mime=(arr[0].match(/:(.*?);/)||[])[1]||'image/png'; const bstr=atob(arr[1]||''); let n=bstr.length; const u8=new Uint8Array(n); while(n--) u8[n]=bstr.charCodeAt(n); resolve(new Blob([u8],{type:mime})); } }catch(e){ reject(e); } }); }
  function JCam_ts(){ const d=new Date(); const p=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}-${p(d.getMinutes())}-${p(d.getSeconds())}`; }
  async function JCam_uniqueName(dir, base){ let name=base, i=1; const dot=base.lastIndexOf('.'); const stem=dot>0? base.slice(0,dot):base; const ext=dot>0? base.slice(dot):''; while(true){ try{ await dir.getFileHandle(name); name=`${stem} (${i})${ext}`; i++; if(i>9999) break; }catch(e){ break; } } return name; }
  async function JCam_save(){ try{ const c=JCamState.canvas; if(!c) return; const blob=await JCam_canvasToBlob(c,'image/png',0.92); const hasOPFS=!!(navigator.storage && navigator.storage.getDirectory); if(!hasOPFS || typeof Photos_dir!=='function'){ const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`Photo ${JCam_ts()}.png`; document.body.appendChild(a); a.click(); setTimeout(()=>{ URL.revokeObjectURL(url); a.remove(); },1000); Desktop_showOverlay?.('Saved (downloaded) ✓'); JCam_retake(); return; } const dir=await Photos_dir(); const baseName=`Photo ${JCam_ts()}.png`; const name=await JCam_uniqueName(dir, baseName); const fh=await dir.getFileHandle(name,{create:true}); const w=await fh.createWritable(); await w.write(blob); await w.close(); Desktop_showOverlay?.('Saved to Photos ✓'); try{ await Photos_refreshGrid(); }catch(e){} JCam_retake(); }catch(e){ console.warn('JCam_save error', e); alert('Save failed: '+(e?.message||String(e))); } }

