// ===== Photos app =====
  const PhotosState={ selecting:false, selected:new Set() };
  async function Desktop_openPhotosApp(){ const app=document.getElementById('photosApp'); app.style.display='block'; await Photos_refreshGrid(); }
  function Photos_close(){ document.getElementById('photosApp').style.display='none'; }
  async function Photos_dir(){ const drive=await UserData_dir(); return await drive.getDirectoryHandle('Photos', {create:true}); }
  function Photos_updateSelectionUI(){ const selectBtn=document.getElementById('photosSelectBtn'); const selectAllBtn=document.getElementById('photosSelectAllBtn'); const deleteBtn=document.getElementById('photosDeleteBtn'); if(selectBtn) selectBtn.textContent=PhotosState.selecting?'Cancel':'Select'; if(selectAllBtn) selectAllBtn.style.display=PhotosState.selecting?'inline-block':'none'; if(deleteBtn){ deleteBtn.style.display=PhotosState.selecting && PhotosState.selected.size?'inline-block':'none'; deleteBtn.textContent=`Delete selected (${PhotosState.selected.size})`; } }
  function Photos_toggleSelect(){ PhotosState.selecting=!PhotosState.selecting; if(!PhotosState.selecting) PhotosState.selected.clear(); Photos_refreshGrid(); }
  async function Photos_selectAll(){ if(!PhotosState.selecting) return; const dir=await Photos_dir(); PhotosState.selected.clear(); for await(const entry of dir.values()){ if(entry.kind==='file'){ const file=await entry.getFile(); if(file.type && file.type.startsWith('image/')) PhotosState.selected.add(entry.name); } } Photos_refreshGrid(); }
  function Photos_toggleItem(name){ if(PhotosState.selected.has(name)) PhotosState.selected.delete(name); else PhotosState.selected.add(name); Photos_refreshGrid(); }
  async function Photos_refreshGrid(){ try{ const grid=document.getElementById('photosBody'); grid.innerHTML=''; const dir=await Photos_dir(); let count=0; for await(const entry of dir.values()){ if(entry.kind==='file'){ const file=await entry.getFile(); if(file.type && file.type.startsWith('image/')){ count++; const url=URL.createObjectURL(file); const tile=document.createElement('div'); tile.className='photo-tile'; const img=document.createElement('img'); img.src=url; img.onload=()=>URL.revokeObjectURL(url); if(PhotosState.selecting){ const check=document.createElement('input'); check.type='checkbox'; check.checked=PhotosState.selected.has(entry.name); check.setAttribute('aria-label',`Select ${entry.name}`); check.onchange=()=>Photos_toggleItem(entry.name); tile.appendChild(check); } tile.appendChild(img); const actions=document.createElement('div'); actions.className='photo-actions'; const setBtn=document.createElement('button'); setBtn.className='explorer-btn'; setBtn.textContent='Set as background'; setBtn.onclick = ()=> Photos_setWallpaperByName(entry.name); const delBtn=document.createElement('button'); delBtn.className='explorer-btn'; delBtn.style.background='#a83434'; delBtn.textContent='Delete'; delBtn.onclick = ()=> Photos_deleteByName(entry.name); actions.appendChild(setBtn); actions.appendChild(delBtn); tile.appendChild(actions); grid.appendChild(tile); } } } if(!count){ grid.innerHTML='<div id="photosEmpty" class="music-empty">No photos yet.</div>'; } Photos_updateSelectionUI(); }catch(e){ alert('Photos error: '+e.message); } }
  async function Photos_deleteByName(name){ try{ const ok=confirm('Delete photo "'+name+'"?'); if(!ok) return; const dir=await Photos_dir(); await dir.removeEntry(name); PhotosState.selected.delete(name); await Photos_refreshGrid(); Desktop_showOverlay?.('Deleted ✓'); }catch(e){ alert('Delete failed: '+e.message); } }
  async function Photos_deleteSelected(){ const names=[...PhotosState.selected]; if(!names.length) return; if(!confirm(`Delete ${names.length} selected photo(s)?`)) return; try{ const dir=await Photos_dir(); for(const name of names){ try{ await dir.removeEntry(name); }catch(e){} } PhotosState.selected.clear(); PhotosState.selecting=false; await Photos_refreshGrid(); Desktop_showOverlay?.(`Deleted ${names.length} photo(s) ✓`); }catch(e){ alert('Delete failed: '+e.message); } }
  async function Photos_setWallpaperByName(name){ try{ const dir=await Photos_dir(); const fh=await dir.getFileHandle(name); const file=await fh.getFile(); const reader=new FileReader(); reader.onload = ()=>{ Desktop_setWallpaperFromData(reader.result); Desktop_hideStartMenu(); }; reader.readAsDataURL(file); }catch(e){ alert('Set background failed: '+e.message); } }
  ready(()=>{ const input=document.getElementById('photosInput'); if(input){ input.addEventListener('change', async (e)=>{ const files=[...e.target.files||[]]; if(!files.length) return; try{ const dir=await Photos_dir(); for(const f of files){ const fh=await dir.getFileHandle(f.name, {create:true}); const w=await fh.createWritable(); await w.write(new Uint8Array(await f.arrayBuffer())); await w.close(); } await Photos_refreshGrid(); alert('Imported '+files.length+' photo(s)'); }catch(err){ alert('Import failed: '+err.message); } finally { input.value=''; } }); } });
